package com.ccd.tljpro;


import com.codename1.components.SpanLabel;
import com.codename1.components.ToastBar;
import com.codename1.io.Log;
import com.codename1.io.Preferences;
import com.codename1.io.Storage;
import com.codename1.l10n.L10NManager;
import com.codename1.social.AppleLogin;
import com.codename1.social.GoogleConnect;
import com.codename1.social.LoginCallback;
import com.codename1.ui.Button;
import com.codename1.ui.ButtonGroup;
import static com.codename1.ui.CN.*;
import com.codename1.ui.Command;
import com.codename1.ui.Component;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.Display;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.RadioButton;
import com.codename1.ui.TextArea;
import com.codename1.ui.TextField;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.geom.Rectangle;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.ui.layouts.FlowLayout;
import com.codename1.ui.layouts.LayeredLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.spinner.Picker;
import com.codename1.ui.table.TableLayout;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.UITimer;
import com.codename1.util.StringUtil;
import java.util.HashMap;
import java.util.Map;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose
 * of building native mobile applications using Java.
 */
public class TuoLaJiPro {
    static public final boolean DEBUG = true;
    static public final boolean BYPASS_LOGIN = false;
    static public final boolean INTERNAL = true;

//    static public final String STORAGE_PROFILE = "profile";

    static public final int GREEN = 0x008000;
//    static public final int DARK_GREEN = 0x0a300a;
    static public final int DARK_GREEN = 0x3c8535;
//    static public final int LIGHT_GREEN = 0x39ad39;
    static public final int LIGHT_GREEN = 0x498057;
    static public final int DARK_BLUE = 0x374b6b;
    static public final int LIGHT_BLUE = 0x54698c;

    static final Map<String, CustomColor> AvailableColors = new HashMap<>();

    static {
        AvailableColors.put("GREEN", new CustomColor("Green", "绿色", GREEN));
        AvailableColors.put("LT_GREEN", new CustomColor("Light Green", "浅绿", LIGHT_GREEN));
        AvailableColors.put("DK_GREEN", new CustomColor("Dark Green", "深绿", DARK_GREEN));
        AvailableColors.put("LT_BLUE", new CustomColor("Light Blue", "浅蓝", LIGHT_BLUE));
        AvailableColors.put("DK_BLUE", new CustomColor("Dark Blue", "深蓝", DARK_BLUE));
    }

    static public int BACKGROUND_COLOR = Card.DEBUG_MODE ? 0xffffff : DARK_BLUE;

    public CustomColor currentColor;
    private Form current;
    public Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });
    }

    public Form formMain = null;
    public TableView formView = null;
    public Form formTable = null;
    public Form formHelp = null;
    public Form formTutor = null;
    public Form formSetting = null;

//    private Label lbTitle;
    private Button btnTutor = null;
    private Button btnPlay = null;
    private Button btnBrowse = null;
    private Button btnPrivateTable = null;
    private Button btnHelp = null;
    private Button btnAccount = null;
//    private Button btnExit = null;
    private Button btnSetting = null;

    public String getMyId() {
        return myId;
    }

    public String getMyName() {
        return myName;
    }

    public void enableButtons() {
        if (this.btnPlay != null) {
            this.btnPlay.setEnabled(true);
            this.btnPlay.setText(Dict.get(lang, "Play"));
//            this.formMain.revalidate();
            if (TuoLaJiPro.DEBUG) Log.p("Enable play button");
        }
        this.tryTimes = 0;
    }

    public void disableButtons() {
        if (this.btnPlay != null) {
            this.btnPlay.setEnabled(false);
            this.btnPlay.setText(Dict.get(lang, "Connecting") + "...");
        }
    }

    public void showPlayButton() {
        if (this.entry.getComponentIndex(this.btnPlay) < 0) {
            this.entry.addComponent(this.entry.getComponentIndex(this.btnHelp), this.btnPlay);
        }
    }

    public void refreshButtons() {
//        this.lbTitle.setText(Dict.get(lang, title));
        this.formMain.setTitle(Dict.get(lang, title));

        if (this.btnPlay.isEnabled()) {
            this.btnPlay.setText(Dict.get(lang, "Play"));
        }
        this.btnBrowse.setText(Dict.get(lang, "Browse"));
        this.btnPrivateTable.setText(Dict.get(lang, Dict.PRIVATE_TABLE));
        this.btnHelp.setText(Dict.get(lang, "Help"));
        this.btnAccount.setText(Dict.get(lang, "Account"));
//        this.btnExit.setText(Dict.get(lang, "Exit"));
        this.btnTutor.setText(Dict.get(lang, "Tutorial"));
        this.btnSetting.setText(Dict.get(lang, "Settings"));
        if (this.player != null) {
            this.player.refreshLang();
        }
    }

    public void validateTable() {
        this.table.forceRevalidate();
    }

    public Form getCurForm() {
        return this.isMainForm ? this.formMain : this.formTable;
    }

    static final String DEFAULT_PLAYER_NAME = "NewPlayer";
    private Player player = null;
    private String myId = "TljProNoID";
    private String myName = DEFAULT_PLAYER_NAME;
    private int tryTimes = 0;
    static final int MAX_TRY_TIMES = 3;

    public void onConnectionError() {
        Player p = this.player;
        if (this.btnPlay != null) {
            this.btnPlay.setEnabled(false);
            this.btnPlay.setText(Dict.get(lang, "Network Error"));
            if (++tryTimes >= MAX_TRY_TIMES) {
                return;
            }
            Button btn = this.btnPlay;
            if (this.currentComp == this.entry) {
                new UITimer(new Runnable() {
                    @Override
                    public void run() {
                        btn.setText(Dict.get(lang, "Connecting") + "...");
                        p.connectServer("");
                    }
                }).schedule(3000, false, this.formMain);
            }
        }
    }

    public String version = "1.0";
    public final static String title = "Langley TuoLaJi Premium";
    public String OS = "";

    public String lang = "en";
    private Container entry;
    private Container table;
    private Container help;
    private Tutor tutor;

    private String errMsg = "";

    private Map<Integer, String> colorIdx = new HashMap<>();
    private String currentColorKey;

    public Image back;
    public void start() {
        if(current != null){
            current.show();
            return;
        }

//        Preferences.setPreferencesLocation(STORAGE_PROFILE);
        if (BYPASS_LOGIN) {
            Preferences.set("UserID", "TestUserID");
            Preferences.set("Email", "TestEmail");
        }

        Display disp = Display.getInstance();

        Object sObj = Storage.getInstance().readObject("lang");
        if (sObj != null) {
            this.lang = sObj.toString();
        } else {
            L10NManager l10n = disp.getLocalizationManager();
            this.lang = l10n.getLanguage();
        }
        if (this.lang == null || this.lang.trim().isEmpty()) this.lang = "en";

        sObj = Storage.getInstance().readObject("myColor");
        if (sObj != null) {
            this.currentColorKey = sObj.toString();
            this.currentColor = AvailableColors.get(this.currentColorKey);
        }

        if (this.currentColor == null) {
            this.currentColorKey = "DK_BLUE";
            this.currentColor = AvailableColors.get(this.currentColorKey);
        }
        BACKGROUND_COLOR = this.currentColor.backColor;

        back = theme.getImage("btn.png");
//        back = back.scaledHeight(Hand.fontRank.getHeight());
//        String onlineHelp = getHelp();
        disp.requestFullScreen();
        disp.setNoSleep(true);
        disp.setScreenSaverEnabled(false);
        disp.setBuiltinSoundsEnabled(true);
        this.version = disp.getProperty("AppVersion", this.version);

        if (DEBUG) {
            System.out.println("Platform=" + disp.getProperty("Platform", ""));
            System.out.println("User-Agent=" + disp.getProperty("User-Agent", ""));
            this.OS = disp.getProperty("OS", "");
            System.out.println("OS=" + this.OS);
        }

        String playerId = getPlayerID();
        if (playerId == null) {
            Dialog.show(Dict.get(lang, "Error"), "Failed to generate Player ID", Dict.get(lang, "OK"), "");
            disp.exitApplication();
        }
        this.myId = playerId;

        this.player = new Player(this);

        this.player.connectServer(true);
    }

    public void showLogin() {
        Display.getInstance().callSerially(() -> {
            if (Card.FOR_IOS) {
                AppleLogin login = new AppleLogin();
                if (login.isUserLoggedIn()) {
                    startMain();
                } else {
                    showAppleLogin(login);
                }
            } else {
//                showGoogleLogin();
                startMain();
            }
        });
    }

    private boolean registered = false;
    private boolean setupDone = false;

    private boolean doRegistration() {
        if (registered) return false;
        registered = Preferences.get("registered", false);
        if (registered) return false;

        String globalId = Preferences.get("UserID", "");
        if (globalId.isEmpty()) {
            this.startRegistration();
        } else {
            this.myName = Preferences.get("Name", this.myName);
            player.sendRequest(player.initRequest(Request.REGISTER)
                    .append("gid", globalId)
                    .append("email", Preferences.get("Email", ""))
                    .append("keyid", Preferences.get("KeyID", ""))
                    .setReSend(true));
            ToastBar.showInfoMessage(Dict.get(lang, Dict.PLEASE_WAIT));
        }
        return true;
    }

    public void finishRegistration() {
        Preferences.set("registered", true);
        registered = true;
        if (!initSetup()) startMain();
    }

    private boolean initSetup() {
        if (setupDone) return false;
        setupDone = Preferences.get("setup", false);
        if (setupDone) return false;

        Display.getInstance().callSerially(() -> {
            showSettings();
        });
        return true;
    }

    private void startMain() {
        if (this.doRegistration()) return;
        if (this.initSetup()) return;

        Display.getInstance().lockOrientation(false);
        Display.getInstance().callSerially(() -> {
            this.createMainForm();

            String playerName = getPlayerName();
            if (playerName.isEmpty()) {
//                this.inputPlayName(playerName);
            } else {
                this.myName = playerName;
            }
            this.formMain.show();

            this.setupTable();

            this.formView = new TableView(this);
//            this.formView.getStyle().setBgColor(BACKGROUND_COLOR);
            this.formView.init();

            this.player.connectServer(Player.OPTION_CHECK);
        });
    }

    private void createMainForm() {
        if (this.formMain == null) {
            Form mainForm = new Form(Dict.get(lang, title), new BorderLayout());
            mainForm.setSafeArea(true);
            if (DEBUG) {
                Rectangle safeRect = mainForm.getSafeArea();
                System.out.print(" x=" + safeRect.getX());
                System.out.print(" y=" + safeRect.getY());
                System.out.print(" w=" + safeRect.getWidth());
                System.out.print(" h=" + safeRect.getHeight());
            }
            this.formMain = mainForm;
            mainForm.getAllStyles().setBgColor(BACKGROUND_COLOR);

            Toolbar topTool = mainForm.getToolbar();
            topTool.setUIID("myTool");

            int menuColor = Player.BUTTON_COLOR;
            Button bPlay = new Button(Dict.get(lang, "Connecting") + "...");
            bPlay.getStyle().setFgColor(menuColor);
            bPlay.getAllStyles().setFont(Hand.fontRank);
            if (this.player.isConnected()) {
                bPlay.setText(Dict.get(lang, "Play"));
            } else {
                bPlay.setEnabled(false);
            }
            this.btnPlay = bPlay;

            FontImage.setMaterialIcon(bPlay, FontImage.MATERIAL_PEOPLE);
            bPlay.addActionListener((e) -> {
                if (!isLandscape()) {
                    return;
                }
                player.sendRequest(Request.create(Request.JOIN, "opt", "").setReSend(true));
            });

            btnBrowse = new Button(Dict.get(lang, "Browse"));
            btnBrowse.getStyle().setFgColor(menuColor);
            btnBrowse.getAllStyles().setFont(Hand.fontRank);
            FontImage.setMaterialIcon(btnBrowse, FontImage.MATERIAL_VIEW_MODULE);
            btnBrowse.addActionListener((e) -> {
                if (!isLandscape()) {
                    return;
                }
                this.switchScene("view");
            });

            btnPrivateTable = new Button(Dict.get(lang, Dict.PRIVATE_TABLE));
            btnPrivateTable.getStyle().setFgColor(menuColor);
            btnPrivateTable.getAllStyles().setFont(Hand.fontRank);
            FontImage.setMaterialIcon(btnPrivateTable, FontImage.MATERIAL_LOCK);
            btnPrivateTable.addActionListener((e) -> {
                if (!isLandscape()) {
                    return;
                }
                this.formView.inputPassword(this.player);
            });

            btnHelp = new Button(Dict.get(lang, "Help"));
            btnHelp.getStyle().setFgColor(menuColor);
//            btnHelp.getAllStyles().setFont(Hand.fontRank);
            FontImage.setMaterialIcon(btnHelp, FontImage.MATERIAL_HELP);
            btnHelp.addActionListener((e) -> {
                if (!isLandscape()) {
                    return;
                }
                showHelp(lang);
            });

            btnAccount = new Button(Dict.get(lang, "Account"));
            btnAccount.getStyle().setFgColor(menuColor);
//            btnAccount.getAllStyles().setFont(Hand.fontRank);
            FontImage.setMaterialIcon(btnAccount, FontImage.MATERIAL_ACCOUNT_CIRCLE);
            btnAccount.addActionListener((e) -> {
                topTool.closeRightSideMenu();
            });

            btnTutor = new Button(Dict.get(lang, "Tutorial"));
            btnTutor.getStyle().setFgColor(menuColor);
            btnTutor.getAllStyles().setFont(Hand.fontRank);
            FontImage.setMaterialIcon(btnTutor, FontImage.MATERIAL_TOUCH_APP);
            btnTutor.addActionListener((e) -> {
                if (!isLandscape()) {
                    return;
                }
                this.switchScene("tutor");
            });

            btnSetting = new Button(Dict.get(lang, "Settings"));
            btnSetting.getStyle().setFgColor(menuColor);
//            btnSetting.getAllStyles().setFont(Hand.fontRank);
            FontImage.setMaterialIcon(btnSetting, FontImage.MATERIAL_SETTINGS);
            btnSetting.addActionListener((e) -> {
                showSettings();
            });

            RadioButton rbEn = new RadioButton("English");
            RadioButton rbZh = new RadioButton("中文");
            ButtonGroup btnGroup = new ButtonGroup(rbEn, rbZh);
            btnGroup.addActionListener((e) -> {
                if (rbEn.isSelected()) {
                    this.lang = "en";
                } else if (rbZh.isSelected()) {
                    this.lang = "zh";
                }
                Storage.getInstance().writeObject("lang", this.lang);
                refreshButtons();
                this.formSetting = null;
                this.formView.resetTableList();
                this.player.sendRequest(this.player.initRequest(Request.LIST));
            });
            if (lang.equalsIgnoreCase("zh")) {
                rbZh.setSelected(true);
            } else {
                rbEn.setSelected(true);
            }

            this.entry = new Container(BoxLayout.yLast());
            this.entry.setSafeArea(true);

            entry.add(this.btnTutor);
            entry.add(this.btnBrowse);
            entry.add(this.btnPlay);
            entry.add(this.btnPrivateTable);
            entry.add(BoxLayout.encloseX(rbEn, rbZh));

            mainForm.add(BorderLayout.CENTER, entry);
            this.currentComp = entry;

            topTool.addComponentToRightSideMenu(btnSetting);
            topTool.addComponentToRightSideMenu(btnHelp);
            topTool.addComponentToRightSideMenu(btnAccount);

            if (INTERNAL) {
                topTool.addMaterialCommandToRightBar("Storage", FontImage.MATERIAL_ECO, (ev) -> {
                    showStorage();
                });
            }
        }
    }

    private void setupTable() {
        this.table = new Container(new LayeredLayout());
        this.table.setSafeArea(true);
        this.player.createTable(this.table);

        this.formTable = new Form("Table", new BorderLayout());
        this.formTable.getStyle().setBgColor(BACKGROUND_COLOR);
        this.formTable.getToolbar().hideToolbar();
        this.formTable.add(BorderLayout.CENTER, this.table);
        this.formTable.revalidate();
    }

    private void inputPlayName(String name) {
        final TextField pName = new TextField(name, Dict.get(lang, "Your Name"), 8, TextArea.ANY);
        pName.setMaxSize(16);
        Command okCmd = new Command(Dict.get(lang, "OK")) {
            @Override
            public void actionPerformed(ActionEvent ev) {
                String playerName = savePlayerName(pName);
                if (playerName == null || playerName.isEmpty()) {
                    Display.getInstance().exitApplication();
                }
                Display.getInstance().callSerially(() -> {
                    switchScene("entry");
                });
            }
        };
        Dialog dlg = new Dialog(Dict.get(lang, "Player Name"));
        dlg.add(pName).add(new Button(okCmd));
        dlg.show();
    }

    void showPlayOption() {
        Object sgObj = Storage.getInstance().readObject("playerName");
        final TextField pName = new TextField("", Dict.get(lang, "Your Name")
                + "(" + Dict.get(lang, Dict.PNAME) + ")", 16, TextArea.ANY);
        pName.setMaxSize(16);
        if (sgObj != null) {
            pName.setText(sgObj.toString());
        }
        Command practiceCmd = new Command(Dict.get(lang, "Practice")) {
            @Override
            public void actionPerformed(ActionEvent ev) {
                String playerName = savePlayerName(pName);
                if (playerName == null) {
                    btnPlay.setEnabled(true);
                    return;
                }
                btnPlay.setEnabled(false);
                player.startPlay(Player.OPTION_PRACTICE);
            }
        };
        FontImage.setMaterialIcon(practiceCmd, FontImage.MATERIAL_DIRECTIONS_WALK, "Button");
        Command matchCmd = new Command(Dict.get(lang, "Match")) {
            @Override
            public void actionPerformed(ActionEvent ev) {
                String playerName = savePlayerName(pName);
                if (playerName == null) {
                    btnPlay.setEnabled(true);
                    return;
                }
                btnPlay.setEnabled(false);
                player.startPlay();
            }
        };
        FontImage.setMaterialIcon(matchCmd, FontImage.MATERIAL_DIRECTIONS_RUN, "Button");
        int finPrac = Player.parseInteger(Storage.getInstance().readObject("finprac"));
        if (finPrac < 1) {
            int totalScore = Player.parseInteger(Storage.getInstance().readObject("tutor_score"));
            if (totalScore >= 80) {
                finPrac = 1;
                Storage.getInstance().writeObject("finprac", 1);
            }
        }
        matchCmd.setEnabled(finPrac > 0);

        Dialog.show("", pName, practiceCmd, matchCmd);
    }

    public Player getPlayer() {
        return player;
    }

    private String savePlayerName(TextField pName) {
        String playerName = pName.getText().trim();
        if (playerName.isEmpty()) {
            this.errMsg = Dict.get(lang, Dict.PLAYER_NAME_REQUIRED);
            return null;
        }
        pName.stopEditing();
        playerName = StringUtil.replaceAll(playerName, "\"", "");
        playerName = StringUtil.replaceAll(playerName, "\\", "");
        playerName = StringUtil.replaceAll(playerName, "'", "");
        playerName = StringUtil.replaceAll(playerName, ":", " ");
        if (playerName.isEmpty()) {
            this.errMsg = Dict.get(lang, Dict.INVALID_PLAYER_NAME);
            return null;
        }
        pName.setText(playerName);
        if (playerName.equals(this.myName)) return playerName;

        Storage.getInstance().writeObject("playerName", playerName);
        this.myName = playerName;
        if (setupDone) player.sendRequest(this.player.initRequest(Request.LIST));
        return playerName;
    }

    private void saveBackground(Picker strPicker) {
        int idx = strPicker.getSelectedStringIndex();
        if (this.colorIdx.get(idx).equals(this.currentColorKey)) {
            return;
        }
        this.currentColorKey = this.colorIdx.get(idx);
        Storage.getInstance().writeObject("myColor", this.currentColorKey);
//        restartApp();
        this.currentColor = AvailableColors.get(this.currentColorKey);
        BACKGROUND_COLOR = this.currentColor.backColor;

        if (!setupDone) return;

        this.formMain.getStyle().setBgColor(BACKGROUND_COLOR);
        this.formTable.getStyle().setBgColor(BACKGROUND_COLOR);
        if (this.formTutor != null) this.formTutor.getStyle().setBgColor(BACKGROUND_COLOR);
        refreshButtons();
    }

    private Component currentComp;
    public boolean isMainForm = true;

    public void switchScene(final String scene) {
        isMainForm = false;
        final TuoLaJiPro app = this;
        switch (scene) {
            case "entry":
                app.formMain.showBack();
                isMainForm = true;
                app.formMain.setGlassPane(null);
                break;
            case "view":
                app.formView.show();
                app.formView.pullTableList();
                break;

            case "table":
                app.formTable.show();
                app.formTable.repaint();
                break;
            case "help":
                app.formHelp.show();
                break;
            case "tutor":
                if (app.formTutor == null) {
                    app.formTutor = new Form("Tutor", new BorderLayout());
                    app.formTutor.setBackCommand("", null, (e) -> {
                        app.switchScene("entry");
                    });
                    app.formTutor.getStyle().setBgColor(BACKGROUND_COLOR);
                    app.formTutor.getToolbar().hideToolbar();
                    app.tutor = new Tutor(app);
                    app.formTutor.addComponent(BorderLayout.CENTER, app.tutor);
                }
                app.tutor.showTopic();
                app.formTutor.show();
                break;
            default:
                break;
        }
    }

    private void showSettings() {
        if (this.formSetting == null) {
            this.formSetting = new Form(Dict.get(lang, "Settings")
                    + " (" + Dict.get(lang, "Version") + " " + this.version + ")");
            this.formSetting.setSafeArea(true);
            TextField pName = new TextField("", Dict.get(lang, "Your Name"), 16, TextArea.ANY);
            pName.setMaxSize(16);
            pName.setText(this.myName.equals(DEFAULT_PLAYER_NAME) ? "" : this.myName);
            TableLayout tl = new TableLayout(2, 2);
            this.formSetting.setLayout(tl);

            String[] bkColors = new String[AvailableColors.keySet().size()];
            int idx = 0;
            for (String k : AvailableColors.keySet()) {
                CustomColor c = AvailableColors.get(k);
                this.colorIdx.put(idx, k);
                bkColors[idx++] = c.getName(lang);
            }

            Picker strPicker = new Picker();
            strPicker.setType(Display.PICKER_TYPE_STRINGS);
            strPicker.setStrings(bkColors);
            strPicker.setSelectedString(this.currentColor.getName(lang));

            this.formSetting.add(tl.createConstraint().widthPercentage(30).horizontalAlign(Component.RIGHT), new Label(Dict.get(lang, "Player Name"))).add(pName)
                    .add(tl.createConstraint().widthPercentage(30).horizontalAlign(Component.RIGHT), new Label(Dict.get(lang, "Background"))).add(strPicker);
//                    .add(tl.createConstraint().widthPercentage(30).horizontalAlign(Component.RIGHT), new Label(Dict.get(lang, "Version"))).add(new Label(this.version));

            Toolbar tbar = this.formSetting.getToolbar();
            tbar.setUIID("myTool");
            if (setupDone) {
                tbar.setBackCommand("", (e) -> {
                    switchScene("entry");
                });
            }
            tbar.addMaterialCommandToRightBar(Dict.get(lang, "Save"), FontImage.MATERIAL_SAVE, (ev) -> {
                String playerName = savePlayerName(pName);
                if (playerName == null) {
                    Dialog.show(Dict.get(lang, "Error"), this.errMsg, Dict.get(lang, "OK"), "");
                    return;
                }
                saveBackground(strPicker);
                if (setupDone) {
                    switchScene("entry");
                } else {
                    setupDone = true;
                    Preferences.set("setup", true);
                    startMain();
                }
            });
        }

        this.formSetting.show();
    }

    private String getPlayerName() {
        Object sgObj = Storage.getInstance().readObject("playerName");
        return sgObj == null ? "" : sgObj.toString();
    }

    private String getPlayerID() {
        String playerId = null;
        try {
//        List<NetworkInterface> all = Collections.list(NetworkInterface.getNetworkInterfaces());
// WifiManager wimanager = (WifiManager) context.getSystemService(Context.WIFI_SERVICE);
//    String macAddress = wimanager.getConnectionInfo().getMacAddress();

            // skip this for now, may implement in future
//            String udid = disp.getUdid();
//            if (udid != null && !udid.trim().isEmpty()) {
//                return udid.trim();
//            }
//            String msisdn = disp.getMsisdn();
//            if (msisdn != null && !msisdn.trim().isEmpty()) {
//                return msisdn.trim();
//            }

            Storage storage = Storage.getInstance();
            Object pId = storage.readObject("playerId");
            if (pId == null || !pId.toString().startsWith("TLJ")) {
                pId = "TLJ" + Long.toString(System.currentTimeMillis(), 16);
                storage.writeObject("playerId", pId);
            }
            playerId = pId.toString();
        } catch (Exception e) {
            Dialog.show("Fail to get player ID", e.getMessage(), "OK", "");
        }
        return playerId;
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }

        if (this.isMainForm || this.player == null || this.player.tableEnded || !this.player.tableOn) {
            destroy();
        }
    }

    public void destroy() {
        if (this.player != null) {
            player.disconnect();
        }
        Display.getInstance().exitApplication();
    }

    private String currentLang;
    private Map<String, Container> helpMap = new HashMap<>();
    private void showHelp(final String lang) {
        if (this.help == null) {
            this.help = new Container(new LayeredLayout());
            this.help.setSafeArea(true);
            this.formHelp = new Form(new BorderLayout());
            this.formHelp.setBackCommand("", null, (e) -> {
                this.switchScene("entry");
            });
//            this.formHelp.getStyle().setBgColor(BACKGROUND_COLOR);
            this.formHelp.getToolbar().hideToolbar();
            this.formHelp.addComponent(BorderLayout.CENTER, this.help);
        } else {
            if (lang.equals(currentLang)) {
                this.switchScene("help");
                return;
            }
            this.help.removeAll();
        }

        Container currentHelp = helpMap.get(lang);

        if (currentHelp == null) {
            switch (lang) {
                case "zh":
                    currentHelp = showHelpZH();
                    break;
                case "en":
                default:
                    currentHelp = showHelpEN();
            }

            helpMap.put(lang, currentHelp);
            currentLang = lang;
        }

        Button bReturn = new Button(Dict.get(lang, "Exit"));
        FontImage.setMaterialIcon(bReturn, FontImage.MATERIAL_EXIT_TO_APP);
//        bReturn.setUIID("return");
        bReturn.addActionListener((e) -> {
            this.switchScene("entry");
        });

        this.help.add(currentHelp).add(bReturn);
        LayeredLayout ll = (LayeredLayout) help.getLayout();
        ll.setInsets(bReturn, "auto 0 0 auto");  //top right bottom left
        this.switchScene("help");
    }

    private Container showHelpZH() {
        Container content = new Container(BoxLayout.y());
        content.setScrollableY(true);
        content.setScrollableX(true);
        content.getAllStyles().setFgColor(0);

        SpanLabel lb = new SpanLabel("本游戏为六人四付找朋友打法，采用竞叫上庄，庄家叫主后拿底牌并扣底，\n然后找一个朋友（也可以不找，一个打五个，打成后升级翻倍）");
        content.add(lb);
        lb = new SpanLabel("如果被闲家抠底，则底牌分翻4倍（对子抠底则再乘以2,三张则再乘3, ...）");
        content.add(lb);
        lb = new SpanLabel("四张相同牌为炸弹，可以炸2对的拖拉机");
        content.add(lb);
        lb = new SpanLabel("拖拉机只能是连对，或者相连的三张/四张，对子和连接的三张不算拖拉机");
        content.add(lb);
        lb = new SpanLabel("甩牌失败扣分，每收回一张扣10分");
        content.add(lb);
        lb = new SpanLabel("当需要跟对子（或三张）时必须跟对，\n如果没有其它对子，但有三张（或四张）则必须拆了跟出");
        content.add(lb);
        return content;
    }

    private Container showHelpEN() {
        Container content = new Container(BoxLayout.y());
        content.setScrollableY(true);
        content.setScrollableX(false);

        SpanLabel lb = new SpanLabel("This game is played by six players,"
                + " using four full decks. Each player is dealt with 35 cards,"
                + " while the remaining 6 cards will be added to the declarer later."
                + " The bidding procedure is similar to Bridge game, each player can bid a specific point or pass."
                + " The declarer is the player who made the final point bid (contract point)."
                + " That means, after this point bid, other players all pass."
                + " Then the declarer choose which suit is trump, or NT means no-trump."
                + " After that, the remaining 6 cards is added to the declarer’s hand."
                + " The declarer then select any 6 cards to throw out, as the hole cards."
                + " At this point, the declarer can define the partner condition:"
                + " e.g. 2nd ♠A, it means who plays the second ♠A will be the declarer’s partner,"
                + " then all other 4 players will be the defenders."
                + " The defenders need collect enough points (equals or greater than the contract point) to beat the contract.");
        content.add(lb);
        Container p = new Container();
        content.add(p);
        p.add(boldText("Playing Stage:"));
        addLongText(p, "The declarer plays the first hand, then each player plays in a counter-clockwise order."
                + " The player who wins this round collects all the points (sum all the point cards played, if any),"
                + " and will be the next leading player, and so on."
                + " If a defender wins the final round and there are point cards in the hole cards,"
                + " the total points in the hole cards will be times by a multiple (4 or more, depends on the winning hand strength) and added the defenders’ collected points."
                + " If the contract is made, the declarer and partner is promoted to next rank,"
                + " otherwise the defenders are promoted to next rank.");

        content.add(theme.getImage("h2.png").scaledWidth(Display.getInstance().getDisplayWidth()));

        content.add(p = new Container());
        p.add(boldText("Point Cards:"));
        addLongText(p, "5 (5 points), 10 and K (10 points). 100 points per deck, total points is 400.");

        content.add(p = new Container());
        p.add(boldText("Card Rank"));
        addLongText(p, "(from low to high): 2, 3, 4 … 10, J, Q, K, A, game rank (not in trump suit), game rank (in trump suit), Black Joker, Red Joker.");

        content.add(p = new Container());
        p.add(boldText("Game Rank:"));
        addLongText(p, "The declarer’s current rank (In general, every player begins from Rank 2)");

        content.add(p = new Container());
        p.add(boldText("Trump:"));
        addLongText(p, "Red Joker, Black Joker and the game rank cards are always trumps (even in a NT game).");
        content.add(p = new Container());
        p.add(boldText("Flop Play:"));
        addLongText(p, "The leading player plays multiple combinations together. To make it a valid play, all the combinations must not be beaten by other players.");
        content.add(p = new Container());
        addLongText(p, "   e.g. the leading player try play ♥A♥K♥K, but another player has ♥A♥A, then the leading player is forced to play ♥K♥K (♥A will be returned to his/her hand), and get a 10 point penalty (each card returned get a 10 point penalty).");
        content.add(p = new Container());
        p.add(boldText("Ruff:"));
        addLongText(p, "A player can ruff by using his/her trump if the leading suit is empty in his/her hand.\n");
        content.add(p = new Container());
        p.add(boldText("Overruff:"));
        addLongText(p, "If the leading hand is a Flop, and two players can ruff, then only the strongest(longest) combination is compared to determine which is the winning hand.");
        content.add(p = new Container());
        addLongText(p, "    e.g. suppose ♥ is trump, game rank is 10");
        content.add(p = new Container());
        addLongText(p, "    a. the leading hand is ♠AQQJJ, one player ruffs with ♥A6655, then another player can overruff with ♥59988");
        content.add(p = new Container());
        addLongText(p, "    b. the leading hand is ♠AAJJ, one player ruffs with ♥JJ99, then another player can overruff with ♥QQ22");

        content.add(p = new Container());
        p.add(boldText("DaGuang:"));
        addLongText(p, "Defenders collected no point, declarer and partner is promoted by 3 ranks.");
        content.add(p = new Container());
        p.add(boldText("XiaoGuang:"));
        addLongText(p, "The total collected points are less than half of the contract point, declarer and partner is promoted by 2 ranks.");
        content.add(p = new Container());
        p.add(boldText("Bounce:"));
        addLongText(p, "The total collected points minus the contract point, for each additional 80 points, the defenders are promoted by 1 more rank.");
        content.add(p = new Container());
        p.add(boldText("1 vs 5:"));
        addLongText(p, "At the beginning of playing stage, the declarer can choose “1 vs 5” (no partner). If the contract is made, the declarer will get double promotion.");
        content.add(p = new Container());
        p.add(boldText("Match:"));
        addLongText(p, "The player whose rank passes Rank A wins the match. A full match (2 -> A) usually takes 3.5 to 4.5 hours.");

        content.add(p = new Container());
        p.add(boldText("Card Combinations\n"));
        content.add(p = new Container());
        p.add(boldText("Single:"));
        addLongText(p, "a single card");
        content.add(p = new Container());
        p.add(boldText("Pair:"));
        addLongText(p, "2 same cards");
        content.add(p = new Container());
        p.add(boldText("Tractor:"));
        addLongText(p, "connected pairs: e.g. 2233, 667788, 5577(while 6 is the game rank), ♠K♠K♠A♠A♥5♥5♠5♠5BBRR (while game rank is 5 and ♠ is trump, B is Black Joker, R is Red Joker)");
        content.add(p = new Container());
        p.add(boldText("Trips:"));
        addLongText(p, "3 same cards (if leaded, other player has to follow a pair if he has no trips to play)");
        content.add(p = new Container());
        p.add(boldText("Quads:"));
        addLongText(p, "4 same cards (bomb, can beat 2-pair tractor; if leaded, the follow play preference is: quads, trips + single, 2-pair tractor, 2 pairs, 1 pair + 2 singles, 4 singles)");
        content.add(p = new Container());
        p.add(boldText("Bulldozer:"));
        addLongText(p, "connected trips (or quads): e.g. 444555, JJJQQQKKK (if leaded, the follow play preference is (for 2-trips bulldozer): 2 trips, 1 trips + 1 pair + 1 single, 2-pair tractor + 2 singles, 2 pairs + 2 singles, 1 pair + 4 singles, 6 singles)");

        return content;
    }

    public static Label boldText(String txt) {
        Label boldLabel = new Label(txt);
        boldLabel.getAllStyles().setFont(Hand.fontGeneral);
        boldLabel.getAllStyles().setFgColor(0);
        return boldLabel;
    }

    private void addLongText(Container p, String txt) {
        while (txt.length() > 0) {
            int idx = txt.indexOf(" ");
            if (idx < 0) {
                p.add(new Label(txt));
                return;
            }
            p.add(new Label(txt.substring(0, idx)));
            txt = txt.substring(idx + 1);
        }
    }

    public boolean isLandscape() {
        int w = Display.getInstance().getDisplayWidth();
        int h = Display.getInstance().getDisplayHeight();
        if (w > h) {
            return true;
        }

        if (lang.equals("zh")) {
            Dialog.show("横屏", "请置于横屏模式", Dict.get(lang, "OK"), null);
        } else {
            Dialog.show("Landscape", "Please rotate to landscape", Dict.get(lang, "OK"), null);
        }
        return false;
    }

    private void showAppleLogin(AppleLogin login) {
        Form frm = new Form(BoxLayout.y());
        frm.setSafeArea(true);
        frm.add(FlowLayout.encloseCenter(new Label(AppleLogin.createAppleLogo(0x0, 15f))));
        Button loginBtn = new Button(Dict.get(lang, Dict.SIGNIN_APPLE));
        AppleLogin.decorateLoginButton(loginBtn, 0x0, 0xffffff);

//        login.addScopes("fullName", "email");
        loginBtn.addActionListener(evt -> {
            ToastBar.showInfoMessage(Dict.get(lang, Dict.PLEASE_WAIT));
            if (BYPASS_LOGIN) {
                startMain();
                return;
            }

            if (!login.isNativeLoginSupported()) {
                ToastBar.showErrorMessage(Dict.get(lang, Dict.UPGRADE_IOS));
                if (DEBUG && INTERNAL) {
                    new UITimer(new Runnable() {
                        @Override
                        public void run() {
                            showStorage();
                        }
                    }).schedule(5000, false, frm);
                }
                return;
            }

            login.doLogin(new LoginCallback() {
                @Override
                public void loginFailed(String errorMessage) {
                    ToastBar.showErrorMessage(errorMessage);
                    if (DEBUG && INTERNAL) {
                        new UITimer(new Runnable() {
                            @Override
                            public void run() {
                                showStorage();
                            }
                        }).schedule(5000, false, frm);
                    }
                }

                @Override
                public void loginSuccessful() {
                    Preferences.set("UserID", login.getUserId());
                    Preferences.set("Email", login.getEmail());
                    Preferences.set("Name", login.getFullName());
                    Preferences.set("KeyID", login.getKeyId());
                    startMain();
                }
            });
        });

        Button regBtn = new Button(Dict.get(lang, Dict.SIGNIN_EMAIL));
//        AppleLogin.decorateLoginButton(regBtn, 0x0, 0xffffff);
        regBtn.addActionListener(evt -> {
            startMain();
        });

        frm.add(FlowLayout.encloseCenter(loginBtn));
        frm.add(FlowLayout.encloseCenter(regBtn));
        frm.show();
    }

    private void startRegistration() {
        String email = Preferences.get("Email", "");
        Form frm;
        if (email.isEmpty()) {
            frm = new Form(Dict.get(lang, Dict.REGISTER), BoxLayout.y());
            TextField tf = new TextField("", Dict.get(lang, Dict.INPUT_EMAIL));
            frm.add(BoxLayout.encloseXCenter(tf, new Button(Command.create(Dict.get(lang, "OK"), null, (ev) -> {
                String s = tf.getText().trim();
                if (s.isEmpty()) return;
                player.sendRequest(player.initRequest(Request.REGISTER)
                        .append("email", s)
                        .setReSend(true));
            })
            )));
        } else {
            frm = new Form(Dict.get(lang, Dict.AUTH), BoxLayout.y());
            TextField tf = new TextField(email, Dict.get(lang, Dict.INPUT_EMAIL));
            frm.add(BoxLayout.encloseXCenter(tf, new Button(Command.create(Dict.get(lang, "OK"), null, (ev) -> {
                String s = tf.getText().trim();
                if (s.isEmpty()) return;
                player.sendRequest(player.initRequest(Request.REGISTER)
                        .append("email", s)
                        .setReSend(true));
            })
            )));
        }

        frm.setSafeArea(true);
        if (INTERNAL) {
            frm.getToolbar().addMaterialCommandToRightBar("Storage", FontImage.MATERIAL_ECO, (ev) -> {
                showStorage();
            });
        }
        frm.show();
    }

    private void showGoogleLogin() {
        Form frm = new Form(BoxLayout.y());

//        frm.add(FlowLayout.encloseCenter(new Label(login.));
        Button loginBtn = new Button(Dict.get(lang, Dict.SIGNIN_GOOGLE));

//        login.addScopes("fullName", "email");
        loginBtn.addActionListener(evt -> {
            ToastBar.showInfoMessage(Dict.get(lang, Dict.PLEASE_WAIT));

            if (BYPASS_LOGIN) {
                startMain();
                return;
            }

            MyGoogleLogin lg = MyGoogleLogin.getInstance();
            lg.init();

            GoogleData uData = new GoogleData();
            lg.setCallback(new LoginCallback() {
                @Override
                public void loginFailed(String errorMessage) {
//                    System.out.println("Login failed: " + errorMessage);
                    ToastBar.showErrorMessage("FAIL: " + errorMessage, 5000);
                    showStorage();
                }

                @Override
                public void loginSuccessful() {
                    uData.fetchData(lg.getAccessToken().getToken(), () -> {
                        Preferences.set("fullName", uData.getName());
                        Preferences.set("uniqueId", uData.getId());
//                        Preferences.set("email", uData.getEmail());
                        startMain();
                    });
//                    ToastBar.showMessage(lg.getAccessToken().getToken(), FontImage.MATERIAL_DONE);
//                    String plName = Player.trimmedString(login.getAccessToken());
//                    Storage.getInstance().writeObject("playerName", plName);
//                    myName = plName;
//                    startMain();
                }
            });

            if (lg.isUserLoggedIn()) {
                ToastBar.showInfoMessage("Loggin already");
                startMain();
            } else {
                lg.doLogin();
            }
        });

        Button loginBtn1 = new Button(Dict.get(lang, Dict.SIGNIN_GOOGLE) + " Org");
        loginBtn1.addActionListener(evt -> {
            ToastBar.showInfoMessage(Dict.get(lang, Dict.PLEASE_WAIT));

            if (BYPASS_LOGIN) {
                startMain();
                return;
            }

            GoogleConnect lg = GoogleConnect.getInstance();
            lg.setClientId(Card.GOOGLE_CLIENT_ID);
            lg.setClientSecret(Card.GOOGLE_CLIENT_SECRET);
//            gc.setRedirectURI("https://www.codenameone.com/oauth2callback");
//            lg.setRedirectURI(DEBUG ? "http://localhost" : "urn:ietf:wg:oauth:2.0:oob");
            lg.setRedirectURI("http://localhost");
            GoogleData uData = new GoogleData();
            lg.setCallback(new LoginCallback() {
                @Override
                public void loginFailed(String errorMessage) {
//                    System.out.println("Login failed: " + errorMessage);
                    ToastBar.showErrorMessage("FAIL: " + errorMessage, 5000);
                    showStorage();
                }

                @Override
                public void loginSuccessful() {
                    uData.fetchData(lg.getAccessToken().getToken(), () -> {
                        Preferences.set("fullName", uData.getName());
                        Preferences.set("uniqueId", uData.getId());
//                        Preferences.set("email", uData.getEmail());
                        startMain();
                    });
                }
            });

            if (lg.isUserLoggedIn()) {
                ToastBar.showInfoMessage("Loggin already");
                startMain();
            } else {
                lg.doLogin();
            }
        });

        if (INTERNAL) frm.add(FlowLayout.encloseCenter(loginBtn));
        frm.add(FlowLayout.encloseCenter(loginBtn1));
        frm.show();
    }

    private void showStorage() {
        Form frm = new Form("Storage", BoxLayout.y());
        frm.setSafeArea(true);
        frm.setScrollableX(true);
        frm.setScrollableY(true);
        Storage sr = Storage.getInstance();
        for (String k : sr.listEntries()) {
            if (k == null || k.isEmpty()) continue;
            String v = Player.trimmedString(sr.readObject(k));
            frm.add(BoxLayout.encloseX(new Label(k), new Label(v.isEmpty() ? "Null" : v),
                    new Button(Command.createMaterial("", FontImage.MATERIAL_DELETE, (ev) -> {
                        sr.writeObject(k, null);
                    }))
            ));

        }

        frm.getToolbar().addMaterialCommandToRightBar("Start", FontImage.MATERIAL_STAR, (e) -> {
            if (formMain == null) {
                startMain();
            } else {
                formMain.showBack();
            }
        });
        frm.show();
    }

    static class CustomColor {

        int backColor;
        int generalColor = Player.BLACK_COLOR;
        int pointColor = Player.POINT_COLOR;
        String nameZh;
        String nameEn;

        CustomColor(String nmEn, String nmZh, int bkColor) {
            this.backColor = bkColor;
            this.nameEn = nmEn;
            this.nameZh = nmZh;

            if (nmEn.contains("Dark")) {
                this.generalColor = 0xb1c4bb;
                this.pointColor = Player.INFO_COLOR;
            }
        }

        public String getName(final String lang) {
            switch (lang) {
                case "zh":
                    return nameZh;
            }

            return nameEn;
        }
    }
}
